theme: jekyll-theme-minimal
title: Arthur's hacky rucksack of random bytes
description: "This \"website\" aims at gathering content I find interesting or am currently
working on. Feel free to contribute!"
