[package]
name = "staticify"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
nom = "7.1.3"
serde = { version = "1.0.210", features = ["derive"] }
serde_yml = "0.0.12"
thiserror = "1.0.64"
